kind: LocalConfig
apiversion: odo.dev/v1alpha1
ComponentSettings:
  Type: dotnet:latest
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  Application: eatondset
  Project: eatondset
  Name: eatondset
  Url:
  - Name: eatondset
    Port: 8080
    Secure: true
