kind: LocalConfig
apiversion: odo.dev/v1alpha1
ComponentSettings:
  Type: dotnet:latest
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  Application: eatondsetdev
  Project: eatondset
  Name: eatondsetdev
  Url:
  - Name: eatondsetdev
    Port: 8080
    Secure: true
